[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "cd culturo-frontend && npm install",
  "cd ../culturo-backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd culturo-frontend && npm run build"
]

[start]
cmd = "python main.py" 